Invoice trigger
RajneeshSamiteon/Commission_Calculator pull request #5
Opened 2023-02-20 16:47 UTC by Dheeraj5861

2023-02-20 18:06 UTC, Dheeraj5861 commented on force-app/main/default/classes/InvoiceDetailTriggerHelper.cls
> +        if( monthlyBreakdown.Tile_Margin_Percentage__c >= 33.0 && monthlyBreakdown.Ancillary_Margin_Percentage__c >= 28.0){
Hardcoded these values just for testing
Will perform a query and get the parameters by query result

2023-02-20 18:07 UTC, Dheeraj5861 commented on force-app/main/default/classes/InvoiceDetailTriggerHelper.cls
> +        if( monthlyBreakdown.Tile_Margin_Percentage__c >= 33.0 && monthlyBreakdown.Ancillary_Margin_Percentage__c >= 28.0){
Hardcoded these values just for testing
Will perform a query and get the parameters by query result

2023-02-21 02:17 UTC, RajneeshSamiteon requested changes

2023-02-21 02:17 UTC, RajneeshSamiteon commented on force-app/main/default/classes/InvoiceDetailTriggerHelper.cls
> +        if( monthlyBreakdown.Tile_Margin_Percentage__c >= 33.0 && monthlyBreakdown.Ancillary_Margin_Percentage__c >= 28.0){
ok

2023-02-21 02:17 UTC, RajneeshSamiteon commented on force-app/main/default/classes/InvoiceDetailTriggerHelper.cls
> +        if( monthlyBreakdown.Tile_Margin_Percentage__c >= 33.0 && monthlyBreakdown.Ancillary_Margin_Percentage__c >= 28.0){
<img width="728" alt="image" src="https://user-images.githubusercontent.com/114494846/220230627-91089fed-46ef-42a6-8f0b-f260855a895b.png">
 some thing like this u should use to get values (once your testing is done)

2023-02-21 05:09 UTC, merged